{{- if .Values.btc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoind-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.btc.storage | default "15Gi" }}
{{- end }}