{{- if .Values.eth_fullnode.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethereum-datadir
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.eth_fullnode.storage.size }}
{{- end }}