{{- if .Values.ltc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecoind-claim
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ltc.storage.size }}
{{- end }}