{{- if .Values.polygon_fullnode.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config-volume
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.polygon_fullnode.heimdall_storage | default "1000Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bor-config-volume
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.polygon_fullnode.bor_storage | default "1000Gi" }}
{{- end }}