apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shkeeper-db-claim
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.shkeeper.storage.size }}