{{ if .Values.doge.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dogecoind
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: jsonrpc
    port: 22555
    protocol: TCP
    targetPort: 22555
  - name: nginx
    port: 5555
    protocol: TCP
    targetPort: 80
  selector:
    app: dogecoind
{{ end }}