{{- if .Values.btc_lightning.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lightning-lnd
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.btc_lightning.lnd.storage.size }}
{{- end }}