{{- if .Values.monero.fullnode.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monerod
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monero.fullnode.monerod.storage.size }}
{{- end }}