{{- if .Values.monero.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: monero-wallet-rpc
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
